In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
filename = '/content/drive/MyDrive/Colab Notebooks/강의자료/강의자료/02. Part1.[파이썬 필수 스킬] 데이터분석의 시작, 전처리 라이브러리/data/korean-idol.xlsx'

In [5]:
pd.read_excel(filename)

      이름     그룹      소속사  성별       생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자 1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자 1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자 1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자 1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자 1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자 1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자 1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자 1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자 1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자 1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자 1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자 1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자 1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자 1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자 1993-03-09  174.0   O   2925442

In [6]:
df = pd.read_csv('http://bit.ly/ds-korean-idol')

In [7]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [8]:
df.columns

Index(['이름', '그룹', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='object')

In [9]:
new_col = ['name', '그룹', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수']

In [10]:
new_col

['name', '그룹', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수']

In [11]:
df.columns

Index(['이름', '그룹', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='object')

In [13]:
df.index

RangeIndex(start=0, stop=15, step=1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       15 non-null     object
 1   그룹       14 non-null     object
 2   소속사      15 non-null     object
 3   성별       15 non-null     object
 4   생년월일     15 non-null     object
 5   키        13 non-null     float64
 6   혈액형      15 non-null     object
 7   브랜드평판지수  15 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.1+ KB

In [15]:
df.describe()

                키       브랜드평판지수
count   13.000000  1.500000e+01
mean   175.792308  5.655856e+06
std      5.820576  2.539068e+06
min    162.100000  2.925442e+06
25%    174.000000  3.712344e+06
50%    177.000000  4.668615e+06
75%    179.200000  7.862214e+06
max    183.000000  1.052326e+07

In [16]:
df.shape

(15, 8)

In [17]:
df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [18]:
df.tail()

     이름     그룹   소속사  성별        생년월일      키 혈액형  브랜드평판지수
10   태연   소녀시대    SM  여자  1989-03-09    NaN   A  3918661
11  차은우   아스트로  판타지오  남자  1997-03-30  183.0   B  3506027
12   백호   뉴이스트  플레디스  남자  1995-07-21  175.0  AB  3301654
13   JR   뉴이스트  플레디스  남자  1995-06-08  176.0   O  3274137
14   슈가  방탄소년단   빅히트  남자  1993-03-09  174.0   O  2925442

In [19]:
df.head(3)

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745

In [20]:
df.tail(2)

    이름     그룹   소속사  성별        생년월일      키 혈액형  브랜드평판지수
13  JR   뉴이스트  플레디스  남자  1995-06-08  176.0   O  3274137
14  슈가  방탄소년단   빅히트  남자  1993-03-09  174.0   O  2925442

In [23]:
df.sort_index()

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [28]:
df.sort_index(ascending=False)

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260

In [31]:
df.sort_values(by='키')

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661

In [32]:
df.sort_values('키')

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661

In [33]:
df.sort_values('키', ascending=False)

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661

In [34]:
df.sort_values(by=['키', '브랜드평판지수'])

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615

In [35]:
df.sort_values(by=['키', '브랜드평판지수'], ascending=False)

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661

In [36]:
df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [37]:
type(df['혈액형'])

pandas.core.series.Series

In [38]:
type(df['이름'])

pandas.core.series.Series

In [40]:
a1 = df['이름']

In [41]:
a1

0       지민
1     지드래곤
2     강다니엘
3        뷔
4       화사
5       정국
6       민현
7       소연
8        진
9      하성운
10      태연
11     차은우
12      백호
13      JR
14      슈가
Name: 이름, dtype: object

In [43]:
a2 = df[0:]

In [44]:
a2

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [45]:
df.이름

0       지민
1     지드래곤
2     강다니엘
3        뷔
4       화사
5       정국
6       민현
7       소연
8        진
9      하성운
10      태연
11     차은우
12      백호
13      JR
14      슈가
Name: 이름, dtype: object

In [46]:
df.loc[:, '이름']

0       지민
1     지드래곤
2     강다니엘
3        뷔
4       화사
5       정국
6       민현
7       소연
8        진
9      하성운
10      태연
11     차은우
12      백호
13      JR
14      슈가
Name: 이름, dtype: object

In [47]:
df.loc[:, ['이름', '생년월일']]

      이름        생년월일
0     지민  1995-10-13
1   지드래곤  1988-08-18
2   강다니엘  1996-12-10
3      뷔  1995-12-30
4     화사  1995-07-23
5     정국  1997-09-01
6     민현  1995-08-09
7     소연  1998-08-26
8      진  1992-12-04
9    하성운  1994-03-22
10    태연  1989-03-09
11   차은우  1997-03-30
12    백호  1995-07-21
13    JR  1995-06-08
14    슈가  1993-03-09

In [48]:
df.loc[3:8, ['이름', '생년월일']]

   이름        생년월일
3   뷔  1995-12-30
4  화사  1995-07-23
5  정국  1997-09-01
6  민현  1995-08-09
7  소연  1998-08-26
8   진  1992-12-04

In [49]:
df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [50]:
df.loc[2:5, '이름':'생년월일']

     이름     그룹  소속사  성별        생년월일
2  강다니엘    NaN  커넥트  남자  1996-12-10
3     뷔  방탄소년단  빅히트  남자  1995-12-30
4    화사    마마무  RBW  여자  1995-07-23
5    정국  방탄소년단  빅히트  남자  1997-09-01

In [51]:
df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [52]:
df.iloc[:, [0, 2]]

      이름      소속사
0     지민      빅히트
1   지드래곤       YG
2   강다니엘      커넥트
3      뷔      빅히트
4     화사      RBW
5     정국      빅히트
6     민현     플레디스
7     소연       큐브
8      진      빅히트
9    하성운  스타크루이엔티
10    태연       SM
11   차은우     판타지오
12    백호     플레디스
13    JR     플레디스
14    슈가      빅히트

In [53]:
df.iloc[1:5, [0, 2]]

     이름  소속사
1  지드래곤   YG
2  강다니엘  커넥트
3     뷔  빅히트
4    화사  RBW

In [54]:
df.iloc[1:5, 1:4]

      그룹  소속사  성별
1     빅뱅   YG  남자
2    NaN  커넥트  남자
3  방탄소년단  빅히트  남자
4    마마무  RBW  여자