In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('https://bit.ly/ds-korean-idol')

In [5]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [8]:
df['키'] > 180

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
Name: 키, dtype: bool

In [9]:
df[df['키'] < 170]

    이름   그룹      소속사  성별        생년월일      키 혈액형  브랜드평판지수
4   화사  마마무      RBW  여자  1995-07-23  162.1   A  7650928
9  하성운   핫샷  스타크루이엔티  남자  1994-03-22  167.1   A  4036489

In [10]:
df[df['키'] > 180]

     이름    그룹   소속사  성별        생년월일      키 혈액형  브랜드평판지수
6    민현  뉴이스트  플레디스  남자  1995-08-09  182.3   O  4989792
11  차은우  아스트로  판타지오  남자  1997-03-30  183.0   B  3506027

In [11]:
df[df['키'] > 180][['이름', '키']]

     이름      키
6    민현  182.3
11  차은우  183.0

In [12]:
df[df['키'] > 180][['이름', '키']]

     이름      키
6    민현  182.3
11  차은우  183.0

In [13]:
df.loc[df['키'] > 180, '이름']

6      민현
11    차은우
Name: 이름, dtype: object

In [14]:
df.loc[df['키'] > 180, '이름':'성별']

     이름    그룹   소속사  성별
6    민현  뉴이스트  플레디스  남자
11  차은우  아스트로  판타지오  남자

In [18]:
df.loc[df['키'] > 180,['이름','성별']]

     이름  성별
6    민현  남자
11  차은우  남자

In [19]:
my_condition = ['플레디스', 'SM']

In [20]:
df['소속사'].isin(my_condition)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10     True
11    False
12     True
13     True
14    False
Name: 소속사, dtype: bool

In [21]:
df.loc[df['소속사'].isin(my_condition)]

    이름    그룹   소속사  성별        생년월일      키 혈액형  브랜드평판지수
6   민현  뉴이스트  플레디스  남자  1995-08-09  182.3   O  4989792
10  태연  소녀시대    SM  여자  1989-03-09    NaN   A  3918661
12  백호  뉴이스트  플레디스  남자  1995-07-21  175.0  AB  3301654
13  JR  뉴이스트  플레디스  남자  1995-06-08  176.0   O  3274137

결측값

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       15 non-null     object
 1   그룹       14 non-null     object
 2   소속사      15 non-null     object
 3   성별       15 non-null     object
 4   생년월일     15 non-null     object
 5   키        13 non-null     float64
 6   혈액형      15 non-null     object
 7   브랜드평판지수  15 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.1+ KB

In [24]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [28]:
df.isna()

       이름     그룹    소속사     성별   생년월일      키    혈액형  브랜드평판지수
0   False  False  False  False  False  False  False    False
1   False  False  False  False  False  False  False    False
2   False   True  False  False  False  False  False    False
3   False  False  False  False  False  False  False    False
4   False  False  False  False  False  False  False    False
5   False  False  False  False  False  False  False    False
6   False  False  False  False  False  False  False    False
7   False  False  False  False  False   True  False    False
8   False  False  False  False  False  False  False    False
9   False  False  False  False  False  False  False    False
10  False  False  False  False  False   True  False    False
11  False  False  False  False  False  False  False    False
12  False  False  False  False  False  False  False    False
13  False  False  False  False  False  False  False    False
14  False  False  False  False  False  False  False    False

In [30]:
df['그룹'].isnull()

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
Name: 그룹, dtype: bool

In [31]:
df['그룹'][df['그룹'].isnull()]

2    NaN
Name: 그룹, dtype: object

In [32]:
df['그룹'][df['그룹'].isna()]

2    NaN
Name: 그룹, dtype: object

In [33]:
df['그룹'].notnull()

0      True
1      True
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
Name: 그룹, dtype: bool

In [34]:
df['그룹'][df['그룹'].notna()]

0     방탄소년단
1        빅뱅
3     방탄소년단
4       마마무
5     방탄소년단
6      뉴이스트
7       아이들
8     방탄소년단
9        핫샷
10     소녀시대
11     아스트로
12     뉴이스트
13     뉴이스트
14    방탄소년단
Name: 그룹, dtype: object

In [35]:
df['그룹'][df['그룹'].notnull()]

0     방탄소년단
1        빅뱅
3     방탄소년단
4       마마무
5     방탄소년단
6      뉴이스트
7       아이들
8     방탄소년단
9        핫샷
10     소녀시대
11     아스트로
12     뉴이스트
13     뉴이스트
14    방탄소년단
Name: 그룹, dtype: object

In [36]:
df['그룹'][df['그룹'].notnull()=True]

SyntaxError: ignored

In [43]:
df.loc[df['그룹'].isnull()]

     이름   그룹  소속사  성별        생년월일      키 혈액형  브랜드평판지수
2  강다니엘  NaN  커넥트  남자  1996-12-10  180.0   A  8273745

In [37]:
df.loc[ df['그룹'].notnull(), ['키', '혈액형'] ]

        키 혈액형
0   173.6   A
1   177.0   A
3   178.0  AB
4   162.1   A
5   178.0   A
6   182.3   O
7     NaN   B
8   179.2   O
9   167.1   A
10    NaN   A
11  183.0   B
12  175.0  AB
13  176.0   O
14  174.0   O

In [44]:
df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [45]:
new_df = df

In [46]:
new_df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [47]:
new_df['이름'] = 0

In [48]:
new_df.head()

   이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0   0  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1   0     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2   0    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3   0  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4   0    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [49]:
df.head()

   이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0   0  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1   0     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2   0    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3   0  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4   0    마마무  RBW  여자  1995-07-23  162.1   A   7650928

이렇게 되면 원본 데이터도 바뀌어버림!!!

In [50]:
hex(id(new_df))

'0x7f9ddf48e208'

In [51]:
hex(id(df))

'0x7f9ddf48e208'

같은 메모리주소를 공유하기 떄문에 함께 수정이 된다!

복사하기 위해서는?

In [53]:
df = pd.read_csv('https://bit.ly/ds-korean-idol')

In [54]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [55]:
copy_df = df.copy()

In [56]:
copy_df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [57]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [58]:
hex(id(copy_df))

'0x7f9dd72d7940'

In [59]:
hex(id(df))

'0x7f9dd5e1f048'

row 및 column 추가/삭제 방법

In [60]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [61]:
df.append({'이름': '테디', '그룹': '테디그룹', '소속사': '끝내주는소속사', '성별': '남자', '생년월일': '1970-01-01', '키': 195.0, '혈액형': 'O', '브랜드평판지수': 12345678}, ignore_index=True)

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
15    테디   테디그룹  끝내주는소속사  남자  1970-01-01  195.0   O  12345678

In [62]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [63]:
df = df.append({'이름': '테디', '그룹': '테디그룹', '소속사': '끝내주는소속사', '성별': '남자', '생년월일': '1970-01-01', '키': 195.0, '혈액형': 'O', '브랜드평판지수': 12345678}, ignore_index=True)

In [64]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
15    테디   테디그룹  끝내주는소속사  남자  1970-01-01  195.0   O  12345678

In [65]:
df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [66]:
df['국적'] = '대한민국'

In [67]:
df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수    국적
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260  대한민국
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947  대한민국
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745  대한민국
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501  대한민국
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928  대한민국

In [68]:
df.loc[ df['이름'] == '지드래곤' , '국적'] = 'korea'

In [69]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수     국적
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260   대한민국
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947  korea
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745   대한민국
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501   대한민국
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928   대한민국
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335   대한민국
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792   대한민국
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615   대한민국
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308   대한민국
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489   대한민국
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661   대한민국
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027   대한민국
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654   대한민국
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137   대한민국
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442   대한민국
15    테디   테디그룹  끝내주는소속사  남자  1970-01-01  195.0   O  12345678   대한민국