In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('https://bit.ly/ds-korean-idol')
df2 = pd.read_csv('https://bit.ly/ds-korean-idol-2')

In [4]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [5]:
df2

      이름    연봉  가족수
0     지민  3000    3
1   지드래곤  3500    3
2   강다니엘  3200    4
3      뷔  3050    4
4     화사  4300    3
5     정국  2900    5
6     민현  3400    6
7     소연  4500    5
8      진  4200    4
9    하성운  4300    4
10    태연  3700    3
11   차은우  3850    5
12    백호  3900    4
13    JR  4100    3
14    슈가  4150    3

In [6]:
df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [7]:
df_copy = df.copy()

In [8]:
df_copy

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [9]:
pd.concat([df, df_copy], sort=False)

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [10]:
df_concat = pd.concat([df, df_copy], sort=False)
df_concat

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [11]:
df_concat.reset_index()

    index    이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0       0    지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1       1  지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2       2  강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3       3     뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4       4    화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5       5    정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6       6    민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7       7    소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8       8     진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9       9   하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10     10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11     11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12     12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13     13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14     14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
15      0    지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
16      1  지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
17      2  강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
18      3     뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
19      4    화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
20      5    정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
21      6    민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
22      7    소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
23      8     진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
24      9   하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
25     10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
26     11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
27     12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
28     13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
29     14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [12]:
df_concat.reset_index(drop=True)

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
15    지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
16  지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
17  강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
18     뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
19    화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
20    정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
21    민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
22    소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
23     진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
24   하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
25    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
26   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
27    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
28    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
29    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [13]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [14]:
df2 = pd.read_csv('https://bit.ly/ds-korean-idol-2')
df2

      이름    연봉  가족수
0     지민  3000    3
1   지드래곤  3500    3
2   강다니엘  3200    4
3      뷔  3050    4
4     화사  4300    3
5     정국  2900    5
6     민현  3400    6
7     소연  4500    5
8      진  4200    4
9    하성운  4300    4
10    태연  3700    3
11   차은우  3850    5
12    백호  3900    4
13    JR  4100    3
14    슈가  4150    3

In [15]:
pd.concat([df, df2], axis=1)

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수    이름    연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260    지민  3000    3
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947  지드래곤  3500    3
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  강다니엘  3200    4
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501     뷔  3050    4
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928    화사  4300    3
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335    정국  2900    5
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792    민현  3400    6
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615    소연  4500    5
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308     진  4200    4
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489   하성운  4300    4
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661    태연  3700    3
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027   차은우  3850    5
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654    백호  3900    4
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137    JR  4100    3
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442    슈가  4150    3

In [16]:
df3 = df2.drop([3, 5])

In [17]:
df3

      이름    연봉  가족수
0     지민  3000    3
1   지드래곤  3500    3
2   강다니엘  3200    4
4     화사  4300    3
6     민현  3400    6
7     소연  4500    5
8      진  4200    4
9    하성운  4300    4
10    태연  3700    3
11   차은우  3850    5
12    백호  3900    4
13    JR  4100    3
14    슈가  4150    3

In [18]:
df2

      이름    연봉  가족수
0     지민  3000    3
1   지드래곤  3500    3
2   강다니엘  3200    4
3      뷔  3050    4
4     화사  4300    3
5     정국  2900    5
6     민현  3400    6
7     소연  4500    5
8      진  4200    4
9    하성운  4300    4
10    태연  3700    3
11   차은우  3850    5
12    백호  3900    4
13    JR  4100    3
14    슈가  4150    3

In [19]:
pd.concat([df, df3], axis=1)

      이름     그룹      소속사  성별        생년월일  ...  혈액형   브랜드평판지수    이름      연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  ...    A  10523260    지민  3000.0  3.0
1   지드래곤     빅뱅       YG  남자  1988-08-18  ...    A   9916947  지드래곤  3500.0  3.0
2   강다니엘    NaN      커넥트  남자  1996-12-10  ...    A   8273745  강다니엘  3200.0  4.0
3      뷔  방탄소년단      빅히트  남자  1995-12-30  ...   AB   8073501   NaN     NaN  NaN
4     화사    마마무      RBW  여자  1995-07-23  ...    A   7650928    화사  4300.0  3.0
5     정국  방탄소년단      빅히트  남자  1997-09-01  ...    A   5208335   NaN     NaN  NaN
6     민현   뉴이스트     플레디스  남자  1995-08-09  ...    O   4989792    민현  3400.0  6.0
7     소연    아이들       큐브  여자  1998-08-26  ...    B   4668615    소연  4500.0  5.0
8      진  방탄소년단      빅히트  남자  1992-12-04  ...    O   4570308     진  4200.0  4.0
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  ...    A   4036489   하성운  4300.0  4.0
10    태연   소녀시대       SM  여자  1989-03-09  ...    A   3918661    태연  3700.0  3.0
11   차은우   아스트로     판타지오  남자  1997-03-30  ...    B   3506027   차은우  3850.0  5.0
12    백호   뉴이스트     플레디스  남자  1995-07-21  ...   AB   3301654    백호  3900.0  4.0
13    JR   뉴이스트     플레디스  남자  1995-06-08  ...    O   3274137    JR  4100.0  3.0
14    슈가  방탄소년단      빅히트  남자  1993-03-09  ...    O   2925442    슈가  4150.0  3.0

[15 rows x 11 columns]

In [24]:
pd.concat([df, df2], axis=1)

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수    이름    연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260    지민  3000    3
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947  지드래곤  3500    3
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  강다니엘  3200    4
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501     뷔  3050    4
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928    화사  4300    3
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335    정국  2900    5
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792    민현  3400    6
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615    소연  4500    5
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308     진  4200    4
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489   하성운  4300    4
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661    태연  3700    3
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027   차은우  3850    5
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654    백호  3900    4
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137    JR  4100    3
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442    슈가  4150    3

In [25]:
df2

      이름    연봉  가족수
0     지민  3000    3
1   지드래곤  3500    3
2   강다니엘  3200    4
3      뷔  3050    4
4     화사  4300    3
5     정국  2900    5
6     민현  3400    6
7     소연  4500    5
8      진  4200    4
9    하성운  4300    4
10    태연  3700    3
11   차은우  3850    5
12    백호  3900    4
13    JR  4100    3
14    슈가  4150    3

In [29]:
 df_right = df2.drop([1, 3, 5, 7, 9], axis=0)

In [28]:
df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [30]:
df2

      이름    연봉  가족수
0     지민  3000    3
1   지드래곤  3500    3
2   강다니엘  3200    4
3      뷔  3050    4
4     화사  4300    3
5     정국  2900    5
6     민현  3400    6
7     소연  4500    5
8      진  4200    4
9    하성운  4300    4
10    태연  3700    3
11   차은우  3850    5
12    백호  3900    4
13    JR  4100    3
14    슈가  4150    3

In [31]:
df_right

      이름    연봉  가족수
0     지민  3000    3
2   강다니엘  3200    4
4     화사  4300    3
6     민현  3400    6
8      진  4200    4
10    태연  3700    3
11   차은우  3850    5
12    백호  3900    4
13    JR  4100    3
14    슈가  4150    3

In [32]:
df_right = df_right.reset_index(drop=True)

In [33]:
df_right

     이름    연봉  가족수
0    지민  3000    3
1  강다니엘  3200    4
2    화사  4300    3
3    민현  3400    6
4     진  4200    4
5    태연  3700    3
6   차은우  3850    5
7    백호  3900    4
8    JR  4100    3
9    슈가  4150    3

In [34]:
df_right

     이름    연봉  가족수
0    지민  3000    3
1  강다니엘  3200    4
2    화사  4300    3
3    민현  3400    6
4     진  4200    4
5    태연  3700    3
6   차은우  3850    5
7    백호  3900    4
8    JR  4100    3
9    슈가  4150    3

In [35]:
pd.concat([df, df_right], axis=1)

      이름     그룹      소속사  성별        생년월일  ...  혈액형   브랜드평판지수    이름      연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  ...    A  10523260    지민  3000.0  3.0
1   지드래곤     빅뱅       YG  남자  1988-08-18  ...    A   9916947  강다니엘  3200.0  4.0
2   강다니엘    NaN      커넥트  남자  1996-12-10  ...    A   8273745    화사  4300.0  3.0
3      뷔  방탄소년단      빅히트  남자  1995-12-30  ...   AB   8073501    민현  3400.0  6.0
4     화사    마마무      RBW  여자  1995-07-23  ...    A   7650928     진  4200.0  4.0
5     정국  방탄소년단      빅히트  남자  1997-09-01  ...    A   5208335    태연  3700.0  3.0
6     민현   뉴이스트     플레디스  남자  1995-08-09  ...    O   4989792   차은우  3850.0  5.0
7     소연    아이들       큐브  여자  1998-08-26  ...    B   4668615    백호  3900.0  4.0
8      진  방탄소년단      빅히트  남자  1992-12-04  ...    O   4570308    JR  4100.0  3.0
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  ...    A   4036489    슈가  4150.0  3.0
10    태연   소녀시대       SM  여자  1989-03-09  ...    A   3918661   NaN     NaN  NaN
11   차은우   아스트로     판타지오  남자  1997-03-30  ...    B   3506027   NaN     NaN  NaN
12    백호   뉴이스트     플레디스  남자  1995-07-21  ...   AB   3301654   NaN     NaN  NaN
13    JR   뉴이스트     플레디스  남자  1995-06-08  ...    O   3274137   NaN     NaN  NaN
14    슈가  방탄소년단      빅히트  남자  1993-03-09  ...    O   2925442   NaN     NaN  NaN

[15 rows x 11 columns]

In [36]:
pd.merge(df, df_right, on='이름', how='left')

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수      연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260  3000.0  3.0
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947     NaN  NaN
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  3200.0  4.0
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501     NaN  NaN
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928  4300.0  3.0
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335     NaN  NaN
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792  3400.0  6.0
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615     NaN  NaN
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308  4200.0  4.0
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489     NaN  NaN
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661  3700.0  3.0
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027  3850.0  5.0
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654  3900.0  4.0
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137  4100.0  3.0
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442  4150.0  3.0

In [37]:
pd.merge(df, df_right, on='이름', how='right')

     이름     그룹   소속사  성별        생년월일      키 혈액형   브랜드평판지수    연봉  가족수
0    지민  방탄소년단   빅히트  남자  1995-10-13  173.6   A  10523260  3000    3
1  강다니엘    NaN   커넥트  남자  1996-12-10  180.0   A   8273745  3200    4
2    화사    마마무   RBW  여자  1995-07-23  162.1   A   7650928  4300    3
3    민현   뉴이스트  플레디스  남자  1995-08-09  182.3   O   4989792  3400    6
4     진  방탄소년단   빅히트  남자  1992-12-04  179.2   O   4570308  4200    4
5    태연   소녀시대    SM  여자  1989-03-09    NaN   A   3918661  3700    3
6   차은우   아스트로  판타지오  남자  1997-03-30  183.0   B   3506027  3850    5
7    백호   뉴이스트  플레디스  남자  1995-07-21  175.0  AB   3301654  3900    4
8    JR   뉴이스트  플레디스  남자  1995-06-08  176.0   O   3274137  4100    3
9    슈가  방탄소년단   빅히트  남자  1993-03-09  174.0   O   2925442  4150    3

In [38]:
pd.merge(df, df_right, on='이름', how='inner')

     이름     그룹   소속사  성별        생년월일      키 혈액형   브랜드평판지수    연봉  가족수
0    지민  방탄소년단   빅히트  남자  1995-10-13  173.6   A  10523260  3000    3
1  강다니엘    NaN   커넥트  남자  1996-12-10  180.0   A   8273745  3200    4
2    화사    마마무   RBW  여자  1995-07-23  162.1   A   7650928  4300    3
3    민현   뉴이스트  플레디스  남자  1995-08-09  182.3   O   4989792  3400    6
4     진  방탄소년단   빅히트  남자  1992-12-04  179.2   O   4570308  4200    4
5    태연   소녀시대    SM  여자  1989-03-09    NaN   A   3918661  3700    3
6   차은우   아스트로  판타지오  남자  1997-03-30  183.0   B   3506027  3850    5
7    백호   뉴이스트  플레디스  남자  1995-07-21  175.0  AB   3301654  3900    4
8    JR   뉴이스트  플레디스  남자  1995-06-08  176.0   O   3274137  4100    3
9    슈가  방탄소년단   빅히트  남자  1993-03-09  174.0   O   2925442  4150    3

In [39]:
pd.merge(df, df_right, on='이름', how='outer')

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수      연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260  3000.0  3.0
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947     NaN  NaN
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  3200.0  4.0
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501     NaN  NaN
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928  4300.0  3.0
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335     NaN  NaN
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792  3400.0  6.0
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615     NaN  NaN
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308  4200.0  4.0
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489     NaN  NaN
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661  3700.0  3.0
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027  3850.0  5.0
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654  3900.0  4.0
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137  4100.0  3.0
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442  4150.0  3.0

In [40]:
df_right.columns = ['성함', '연봉', '가족수']

In [41]:
df_right

     성함    연봉  가족수
0    지민  3000    3
1  강다니엘  3200    4
2    화사  4300    3
3    민현  3400    6
4     진  4200    4
5    태연  3700    3
6   차은우  3850    5
7    백호  3900    4
8    JR  4100    3
9    슈가  4150    3

In [42]:
pd.merge(df, df_right, left_on='이름', right_on='성함', how='outer')

      이름     그룹      소속사  성별        생년월일  ...  혈액형   브랜드평판지수    성함      연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  ...    A  10523260    지민  3000.0  3.0
1   지드래곤     빅뱅       YG  남자  1988-08-18  ...    A   9916947   NaN     NaN  NaN
2   강다니엘    NaN      커넥트  남자  1996-12-10  ...    A   8273745  강다니엘  3200.0  4.0
3      뷔  방탄소년단      빅히트  남자  1995-12-30  ...   AB   8073501   NaN     NaN  NaN
4     화사    마마무      RBW  여자  1995-07-23  ...    A   7650928    화사  4300.0  3.0
5     정국  방탄소년단      빅히트  남자  1997-09-01  ...    A   5208335   NaN     NaN  NaN
6     민현   뉴이스트     플레디스  남자  1995-08-09  ...    O   4989792    민현  3400.0  6.0
7     소연    아이들       큐브  여자  1998-08-26  ...    B   4668615   NaN     NaN  NaN
8      진  방탄소년단      빅히트  남자  1992-12-04  ...    O   4570308     진  4200.0  4.0
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  ...    A   4036489   NaN     NaN  NaN
10    태연   소녀시대       SM  여자  1989-03-09  ...    A   3918661    태연  3700.0  3.0
11   차은우   아스트로     판타지오  남자  1997-03-30  ...    B   3506027   차은우  3850.0  5.0
12    백호   뉴이스트     플레디스  남자  1995-07-21  ...   AB   3301654    백호  3900.0  4.0
13    JR   뉴이스트     플레디스  남자  1995-06-08  ...    O   3274137    JR  4100.0  3.0
14    슈가  방탄소년단      빅히트  남자  1993-03-09  ...    O   2925442    슈가  4150.0  3.0

[15 rows x 11 columns]

In [43]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [44]:
df_right

     성함    연봉  가족수
0    지민  3000    3
1  강다니엘  3200    4
2    화사  4300    3
3    민현  3400    6
4     진  4200    4
5    태연  3700    3
6   차은우  3850    5
7    백호  3900    4
8    JR  4100    3
9    슈가  4150    3

In [45]:
df = pd.read_csv('http://bit.ly/ds-korean-idol')

In [46]:
df

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [47]:
df.info

<bound method DataFrame.info of       이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442>

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       15 non-null     object
 1   그룹       14 non-null     object
 2   소속사      15 non-null     object
 3   성별       15 non-null     object
 4   생년월일     15 non-null     object
 5   키        13 non-null     float64
 6   혈액형      15 non-null     object
 7   브랜드평판지수  15 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.1+ KB

In [49]:
df['키'].dtypes

dtype('float64')

In [50]:
df['키'].astype(int)

ValueError: ignored

In [51]:
df['키'] = df['키'].fillna(-1)

In [52]:
df['키'].astype(object)

0     173.6
1       177
2       180
3       178
4     162.1
5       178
6     182.3
7        -1
8     179.2
9     167.1
10       -1
11      183
12      175
13      176
14      174
Name: 키, dtype: object

In [53]:
df['키'].dtypes

dtype('float64')

In [54]:
df['키'].astype(object)

0     173.6
1       177
2       180
3       178
4     162.1
5       178
6     182.3
7        -1
8     179.2
9     167.1
10       -1
11      183
12      175
13      176
14      174
Name: 키, dtype: object

In [58]:
df['키'] =df['키'].astype(int)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       15 non-null     object
 1   그룹       14 non-null     object
 2   소속사      15 non-null     object
 3   성별       15 non-null     object
 4   생년월일     15 non-null     object
 5   키        15 non-null     int64
 6   혈액형      15 non-null     object
 7   브랜드평판지수  15 non-null     int64
dtypes: int64(2), object(6)
memory usage: 1.1+ KB

In [60]:
df

      이름     그룹      소속사  성별        생년월일    키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182   O   4989792
7     소연    아이들       큐브  여자  1998-08-26   -1   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09   -1   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174   O   2925442

In [61]:
df['생년월일']

0     1995-10-13
1     1988-08-18
2     1996-12-10
3     1995-12-30
4     1995-07-23
5     1997-09-01
6     1995-08-09
7     1998-08-26
8     1992-12-04
9     1994-03-22
10    1989-03-09
11    1997-03-30
12    1995-07-21
13    1995-06-08
14    1993-03-09
Name: 생년월일, dtype: object

In [65]:
df['생년월일'] = pd.to_datetime(df['생년월일'])

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       15 non-null     object
 1   그룹       14 non-null     object
 2   소속사      15 non-null     object
 3   성별       15 non-null     object
 4   생년월일     15 non-null     datetime64[ns]
 5   키        15 non-null     int64
 6   혈액형      15 non-null     object
 7   브랜드평판지수  15 non-null     int64
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 1.1+ KB

데이터타입의 생년월일을 월일요일 추출해보기

In [70]:
df['생년월일'].dt

In [71]:
df['생년월일'].dt.year

0     1995
1     1988
2     1996
3     1995
4     1995
5     1997
6     1995
7     1998
8     1992
9     1994
10    1989
11    1997
12    1995
13    1995
14    1993
Name: 생년월일, dtype: int64

In [72]:
df['생년월일'].dt.month

0     10
1      8
2     12
3     12
4      7
5      9
6      8
7      8
8     12
9      3
10     3
11     3
12     7
13     6
14     3
Name: 생년월일, dtype: int64

In [73]:
df['생년월일'].dt.day

0     13
1     18
2     10
3     30
4     23
5      1
6      9
7     26
8      4
9     22
10     9
11    30
12    21
13     8
14     9
Name: 생년월일, dtype: int64

In [74]:
df['생년월일'].dt.hour

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
Name: 생년월일, dtype: int64

In [75]:
df['생년월일'].dt.dayofweek

0     4
1     3
2     1
3     5
4     6
5     0
6     2
7     2
8     4
9     1
10    3
11    6
12    4
13    3
14    1
Name: 생년월일, dtype: int64

In [76]:
df['생년월일'].dt.weekofyear

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  """Entry point for launching an IPython kernel.

0     41
1     33
2     50
3     52
4     29
5     36
6     32
7     35
8     49
9     12
10    10
11    13
12    29
13    23
14    10
Name: 생년월일, dtype: int64

In [77]:
df['생일_년'] = df['생년월일'].dt.year
df['생일_월'] = df['생년월일'].dt.month
df['생일_일'] = df['생년월일'].dt.day

In [ ]:
df