In [1]:
import pandas as pd

In [2]:
CCTV_Seoul = pd.read_csv('C:/Users/woowahan/Documents/data/Python/datamassage/cctv.csv', encoding = 'utf8')

In [3]:
CCTV_Seoul.head()

     기관명       소계 2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강 남 구   5,221    1,944   195.0  316.0   430   546.0  765.0  577.0  448.0
1  강 동 구   1,879      303   387.0  134.0    59   144.0  194.0  273.0  385.0
2  강 북 구   1,265      243    88.0  141.0    74   145.0  254.0    1.0  319.0
3  강 서 구   1,617      219   155.0  118.0   230   187.0  190.0  264.0  254.0
4  관 악 구   3,985      430    56.0  419.0   487   609.0  619.0  694.0  671.0

In [4]:
pop_seoul=pd.read_excel('C:/Users/woowahan/Documents/data/Python/datamassage/pop_seoul.xlsx', enconding='utf-8' )

In [5]:
pop_seoul.head()

,기준일ID,시군구코드,시군구명,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
0,20201218,11000,서울시,1.090282e+07,1.043842e+07,379579.3655,84819.9178,1.116026e+07,1.063678e+07,1.112032e+07,1.074746e+07,5.574969e+06,1.250712e+06,2.058656e+06,2.265601e+06
1,20201218,11110,종로구,2.851009e+05,2.670721e+05,15486.6770,2542.1083,3.701797e+05,2.206032e+05,3.494647e+05,2.391268e+05,2.337545e+05,5.314368e+04,3.233038e+04,1.482805e+05
2,20201218,11140,중구,2.783933e+05,2.520432e+05,18976.8810,7373.2515,3.961259e+05,1.902078e+05,3.685337e+05,2.140073e+05,2.776604e+05,6.765127e+04,3.103768e+04,1.789715e+05
3,20201218,11170,용산구,3.013044e+05,2.797843e+05,18205.2012,3314.9219,3.232275e+05,2.766007e+05,3.209562e+05,2.872674e+05,1.695602e+05,4.111844e+04,4.683125e+04,8.161048e+04
4,20201218,11200,성동구,3.594109e+05,3.425431e+05,15032.8670,1834.9967,3.756175e+05,3.388085e+05,3.740402e+05,3.489614e+05,1.918945e+05,3.481653e+04,5.858649e+04,9.849144e+04

In [6]:
pop_seoul.drop([0], inplace=True)

In [7]:
pop_seoul

,기준일ID,시군구코드,시군구명,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
1,20201218,11110,종로구,285100.9320,267072.1466,15486.6770,2542.1083,3.701797e+05,220603.1741,349464.6706,239126.8330,233754.5464,53143.6773,32330.3759,148280.4932
2,20201218,11140,중구,278393.2846,252043.1521,18976.8810,7373.2515,3.961259e+05,190207.8422,368533.6508,214007.3086,277660.4211,67651.2659,31037.6768,178971.4784
3,20201218,11170,용산구,301304.4117,279784.2886,18205.2012,3314.9219,3.232275e+05,276600.6972,320956.2116,287267.4119,169560.1646,41118.4382,46831.2450,81610.4814
4,20201218,11200,성동구,359410.9331,342543.0694,15032.8670,1834.9967,3.756175e+05,338808.5386,374040.2438,348961.4254,191894.4580,34816.5301,58586.4911,98491.4368
5,20201218,11215,광진구,380801.7989,359331.6158,19795.5445,1674.6386,3.966098e+05,356702.2293,363855.8033,392906.0814,161528.0975,28939.9726,73814.0754,58774.0495
6,20201218,11230,동대문구,380626.5265,352523.2585,23108.2471,4995.0209,3.862391e+05,374270.0723,379113.1042,381707.5424,180432.2529,26996.0977,74792.0700,78644.0852
7,20201218,11260,중랑구,363625.5662,356752.9155,6261.8099,610.8408,3.949137e+05,326603.2257,335405.9281,383782.4506,152115.2114,23149.1755,91380.5422,37585.4937
8,20201218,11290,성북구,442839.3882,423466.9152,15555.2003,3817.2727,4.660072e+05,413734.0573,420610.6309,458717.0720,173486.6077,19322.0599,87024.0998,67140.4480
9,20201218,11305,강북구,303600.4687,297630.8965,4991.1925,978.3796,3.277567e+05,278550.6017,283538.4636,317930.4723,174258.1309,11182.4445,120265.5768,42810.1096
10,20201218,11320,도봉구,280932.0730,277410.3784,2980.3546,541.3400,2.987454e+05,258035.4419,263429.7449,293433.7358,127152.5356,16617.0804,70363.7882,40171.6670
11,20201218,11350,노원구,523749.5455,517147.5301,5224.2989,1377.7166,5.590355e+05,485932.7695,492905.4231,545781.0616,196914.3357,30699.0948,115063.4192,51151.8217
12,20201218,11380,은평구,451182.6804,443588.3717,6551.8835,1042.4252,4.952217e+05,400122.4451,410908.2954,479950.0984,167075.0265,27131.8198,107128.5883,32814.6184
13,20201218,11410,서대문구,391778.5713,359811.0256,20091.6381,11875.9076,4.039317e+05,382960.5219,396889.6907,388127.7717,198307.1585,36521.1715,68432.4914,93353.4956
14,20201218,11440,마포구,465006.1831,440397.4417,19470.3099,5138.4315,4.942586e+05,439344.2662,487483.0330,448951.2904,258560.2631,58555.7531,81201.9222,118802.5878
15,20201218,11470,양천구,396299.2014,389546.8481,5538.8830,1213.4703,4.175998e+05,370414.7632,376306.7099,410579.5525,161633.2853,28276.7502,76155.8902,57200.6449
16,20201218,11500,강서구,552367.0525,538674.1373,9920.0463,3772.8688,5.715399e+05,531737.5213,535671.2238,564292.6444,234965.2826,58906.2984,114264.4276,61794.5566
17,20201218,11530,구로구,421796.4731,389060.1354,28053.5749,4682.7628,4.318368e+05,410663.5848,417002.2780,425220.8981,199840.1577,60830.8843,74100.6733,64908.6001
18,20201218,11545,금천구,243863.6392,225054.6774,16850.0597,1958.9021,2.686106e+05,220799.1019,265339.2373,228523.9263,153237.2637,57191.3059,43362.1636,52683.7942
19,20201218,11560,영등포구,498306.6042,458884.2265,33710.7774,5711.6003,5.562908e+05,445497.6713,547838.6676,462926.5589,320088.7444,81636.7105,87418.6940,151033.3399
20,20201218,11590,동작구,396958.4707,380318.2077,14341.2292,2299.0338,4.245091e+05,364876.7632,371915.4686,414846.3294,144478.8681,25842.4526,58818.3922,59818.0233
21,20201218,11620,관악구,500782.4162,476404.2193,21490.7887,2887.4082,5.454009e+05,445482.0767,457732.7450,531532.1813,191509.6101,29751.2280,107270.6138,54487.7683
22,20201218,11650,서초구,589283.4725,571307.4027,13891.7499,4084.3200,6.970919e+05,493289.7865,676021.3779,527327.8258,395915.8135,121814.9169,83270.4525,190830.4441
23,20201218,11680,강남구,822182.9472,795048.6507,20360.3987,6773.8978,1.020180e+06,664532.4273,978931.0146,710220.0419,584505.4922,177988.2080,114274.9601,292242.3241
24,20201218,11710,송파구,761682.7816,743595.4558,14900.9335,3186.3924,7.682910e+05,752024.7790,764085.0082,759966.9055,355488.7881,94273.3480,150878.6975,110336.7426
25,20201218,11740,강동구,510946.4218,501025.5936,8788.8187,1132.0095,5.413924e+05,474628.0847,482343.8253,531376.8479,207978.7189,43239.6579,121288.7477,43450.3133

In [8]:
CCTV_Seoul.rename(columns={CCTV_Seoul.columns[0] : '시군구명'}, inplace=True)

In [9]:
CCTV_Seoul.head()

    시군구명       소계 2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강 남 구   5,221    1,944   195.0  316.0   430   546.0  765.0  577.0  448.0
1  강 동 구   1,879      303   387.0  134.0    59   144.0  194.0  273.0  385.0
2  강 북 구   1,265      243    88.0  141.0    74   145.0  254.0    1.0  319.0
3  강 서 구   1,617      219   155.0  118.0   230   187.0  190.0  264.0  254.0
4  관 악 구   3,985      430    56.0  419.0   487   609.0  619.0  694.0  671.0

In [10]:
data_result = pd.merge(CCTV_Seoul, pop_seoul, on='시군구명')

In [11]:
data_result.head()

,시군구명,소계,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,...,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
0,동대문구,"2,003",NaN,NaN,NaN,"1,326",111.0,233.0,136.0,197.0,...,23108.2471,4995.0209,386239.0668,374270.0723,379113.1042,381707.5424,180432.2529,26996.0977,74792.0700,78644.0852
1,서대문구,"2,121",565,233.0,214.0,114,109.0,277.0,415.0,194.0,...,20091.6381,11875.9076,403931.7298,382960.5219,396889.6907,388127.7717,198307.1585,36521.1715,68432.4914,93353.4956
2,영등포구,"2,495",132,121.0,206.0,217,366.0,289.0,371.0,793.0,...,33710.7774,5711.6003,556290.8101,445497.6713,547838.6676,462926.5589,320088.7444,81636.7105,87418.6940,151033.3399

In [14]:
del data_result['2011년 이전']

KeyError: '2011년 이전'

In [16]:
data_result.head(2)

,시군구명,소계,2012년,2013년,2014년,2015년,2016년,2017년,2018년,기준일ID,...,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
0,동대문구,"2,003",NaN,NaN,"1,326",111.0,233.0,136.0,197.0,20201218,...,23108.2471,4995.0209,386239.0668,374270.0723,379113.1042,381707.5424,180432.2529,26996.0977,74792.0700,78644.0852
1,서대문구,"2,121",233.0,214.0,114,109.0,277.0,415.0,194.0,20201218,...,20091.6381,11875.9076,403931.7298,382960.5219,396889.6907,388127.7717,198307.1585,36521.1715,68432.4914,93353.4956

In [21]:
del data_result['2012년']

In [22]:
del data_result['2013년']
del data_result['2014년']
del data_result['2015년']
del data_result['2016년']
del data_result['2017년']
del data_result['2018년']

In [23]:
data_result.head(2)

,시군구명,소계,기준일ID,시군구코드,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
0,동대문구,"2,003",20201218,11230,380626.5265,352523.2585,23108.2471,4995.0209,386239.0668,374270.0723,379113.1042,381707.5424,180432.2529,26996.0977,74792.0700,78644.0852
1,서대문구,"2,121",20201218,11410,391778.5713,359811.0256,20091.6381,11875.9076,403931.7298,382960.5219,396889.6907,388127.7717,198307.1585,36521.1715,68432.4914,93353.4956

In [24]:
data_result.set_index('시군구명', inplace=True)

In [25]:
data_result.head()

,소계,기준일ID,시군구코드,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
시군구명,,,,,,,,,,,,,,,
동대문구,"2,003",20201218,11230,380626.5265,352523.2585,23108.2471,4995.0209,386239.0668,374270.0723,379113.1042,381707.5424,180432.2529,26996.0977,74792.0700,78644.0852
서대문구,"2,121",20201218,11410,391778.5713,359811.0256,20091.6381,11875.9076,403931.7298,382960.5219,396889.6907,388127.7717,198307.1585,36521.1715,68432.4914,93353.4956
영등포구,"2,495",20201218,11560,498306.6042,458884.2265,33710.7774,5711.6003,556290.8101,445497.6713,547838.6676,462926.5589,320088.7444,81636.7105,87418.6940,151033.3399

In [26]:
del data_result['시군구코드']

In [27]:
data_result.head(1)

,소계,기준일ID,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
시군구명,,,,,,,,,,,,,,
동대문구,"2,003",20201218,380626.5265,352523.2585,23108.2471,4995.0209,386239.0668,374270.0723,379113.1042,381707.5424,180432.2529,26996.0977,74792.07,78644.0852

In [28]:
del data_result['기준일ID']
del data_result['일최대인구수']
del data_result['일최소인구수']
del data_result['주간인구수(09~18)']

In [29]:
data_result.head(1)

,소계,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
시군구명,,,,,,,,,,
동대문구,"2,003",380626.5265,352523.2585,23108.2471,4995.0209,381707.5424,180432.2529,26996.0977,74792.07,78644.0852

In [30]:
del data_result['야간인구수(19~08)']

In [36]:
data_result.head(1)

,소계,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대이동인구수,자치구간이동인구수
시군구명,,,,,,,
동대문구,"2,003",380626.5265,352523.2585,23108.2471,4995.0209,180432.2529,78644.0852

In [37]:
data_result['외국인생활인구수'] = data_result['총생활인구수'] - data_result['내국인생활인구수']

In [38]:
data_result.head(1)

,소계,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대이동인구수,자치구간이동인구수,외국인생활인구수
시군구명,,,,,,,,
동대문구,"2,003",380626.5265,352523.2585,23108.2471,4995.0209,180432.2529,78644.0852,28103.268

In [39]:
data_result['외국인생활인구수비율'] = data_result['외국인생활인구수'] / data_result['총생활인구수'] * 100

In [40]:
data_result.head(1)

,소계,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대이동인구수,자치구간이동인구수,외국인생활인구수,외국인생활인구수비율
시군구명,,,,,,,,,
동대문구,"2,003",380626.5265,352523.2585,23108.2471,4995.0209,180432.2529,78644.0852,28103.268,7.383423

In [41]:
data_result['내국인생활인구수비율'] = data_result['내국인생활인구수'] / data_result['총생활인구수'] * 100

In [42]:
import numpy as np

In [50]:
np.corrcoef(data_result['외국인생활인구수비율'], data_result['소계'])

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [55]:
data_result['소계1'] = pd.to_numeric(data_result['소계'])

ValueError: Unable to parse string " 2,003 " at position 0

In [56]:
data_result[data_result['소계'].isnull()]

Empty DataFrame
Columns: [소계, 총생활인구수, 내국인생활인구수, 장기체류외국인인구수, 단기체류외국인인구수, 일최대이동인구수, 자치구간이동인구수, 외국인생활인구수, 외국인생활인구수비율, 내국인생활인구수비율]
Index: []