In [1]:
import pandas as pd

In [2]:
CCTV_Seoul = pd.read_csv('C:/Users/woowahan/Documents/data/Python/datamassage/cctv.csv', encoding = 'utf8')

In [3]:
pop_seoul=pd.read_excel('C:/Users/woowahan/Documents/data/Python/datamassage/pop_seoul.xlsx', enconding='utf-8' )

In [4]:
pop_seoul.drop([0], inplace=True)

In [5]:
CCTV_Seoul.rename(columns={CCTV_Seoul.columns[0] : '시군구명'}, inplace=True)

In [6]:
CCTV_Seoul.head()

    시군구명       소계 2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강 남 구   5,221    1,944   195.0  316.0   430   546.0  765.0  577.0  448.0
1  강 동 구   1,879      303   387.0  134.0    59   144.0  194.0  273.0  385.0
2  강 북 구   1,265      243    88.0  141.0    74   145.0  254.0    1.0  319.0
3  강 서 구   1,617      219   155.0  118.0   230   187.0  190.0  264.0  254.0
4  관 악 구   3,985      430    56.0  419.0   487   609.0  619.0  694.0  671.0

In [7]:
pop_seoul.head()

,기준일ID,시군구코드,시군구명,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
1,20201218,11110,종로구,285100.9320,267072.1466,15486.6770,2542.1083,370179.7235,220603.1741,349464.6706,239126.8330,233754.5464,53143.6773,32330.3759,148280.4932
2,20201218,11140,중구,278393.2846,252043.1521,18976.8810,7373.2515,396125.9320,190207.8422,368533.6508,214007.3086,277660.4211,67651.2659,31037.6768,178971.4784
3,20201218,11170,용산구,301304.4117,279784.2886,18205.2012,3314.9219,323227.4861,276600.6972,320956.2116,287267.4119,169560.1646,41118.4382,46831.2450,81610.4814
4,20201218,11200,성동구,359410.9331,342543.0694,15032.8670,1834.9967,375617.4780,338808.5386,374040.2438,348961.4254,191894.4580,34816.5301,58586.4911,98491.4368
5,20201218,11215,광진구,380801.7989,359331.6158,19795.5445,1674.6386,396609.8374,356702.2293,363855.8033,392906.0814,161528.0975,28939.9726,73814.0754,58774.0495

In [8]:
data_result = pd.merge(CCTV_Seoul, pop_seoul, on='시군구명')

In [9]:
data_result.head()

,시군구명,소계,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,...,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
0,동대문구,"2,003",NaN,NaN,NaN,"1,326",111.0,233.0,136.0,197.0,...,23108.2471,4995.0209,386239.0668,374270.0723,379113.1042,381707.5424,180432.2529,26996.0977,74792.0700,78644.0852
1,서대문구,"2,121",565,233.0,214.0,114,109.0,277.0,415.0,194.0,...,20091.6381,11875.9076,403931.7298,382960.5219,396889.6907,388127.7717,198307.1585,36521.1715,68432.4914,93353.4956
2,영등포구,"2,495",132,121.0,206.0,217,366.0,289.0,371.0,793.0,...,33710.7774,5711.6003,556290.8101,445497.6713,547838.6676,462926.5589,320088.7444,81636.7105,87418.6940,151033.3399

In [10]:
data_result.set_index('시군구명', inplace=True)

In [11]:
data_result.head()

,소계,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,기준일ID,...,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
시군구명,,,,,,,,,,,,,,,,,,,,,
동대문구,"2,003",NaN,NaN,NaN,"1,326",111.0,233.0,136.0,197.0,20201218,...,23108.2471,4995.0209,386239.0668,374270.0723,379113.1042,381707.5424,180432.2529,26996.0977,74792.0700,78644.0852
서대문구,"2,121",565,233.0,214.0,114,109.0,277.0,415.0,194.0,20201218,...,20091.6381,11875.9076,403931.7298,382960.5219,396889.6907,388127.7717,198307.1585,36521.1715,68432.4914,93353.4956
영등포구,"2,495",132,121.0,206.0,217,366.0,289.0,371.0,793.0,20201218,...,33710.7774,5711.6003,556290.8101,445497.6713,547838.6676,462926.5589,320088.7444,81636.7105,87418.6940,151033.3399

In [12]:
del data_result['기준일ID']
del data_result['일최대인구수']
del data_result['일최소인구수']
del data_result['주간인구수(09~18)']
del data_result['시군구코드']
del data_result['야간인구수(19~08)']

In [13]:
data_result.head()

,소계,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
시군구명,,,,,,,,,,,,,,,,,
동대문구,"2,003",NaN,NaN,NaN,"1,326",111.0,233.0,136.0,197.0,380626.5265,352523.2585,23108.2471,4995.0209,180432.2529,26996.0977,74792.0700,78644.0852
서대문구,"2,121",565,233.0,214.0,114,109.0,277.0,415.0,194.0,391778.5713,359811.0256,20091.6381,11875.9076,198307.1585,36521.1715,68432.4914,93353.4956
영등포구,"2,495",132,121.0,206.0,217,366.0,289.0,371.0,793.0,498306.6042,458884.2265,33710.7774,5711.6003,320088.7444,81636.7105,87418.6940,151033.3399

In [14]:
del data_result['2013년']
del data_result['2014년']
del data_result['2015년']
del data_result['2016년']
del data_result['2017년']
del data_result['2018년']

In [15]:
data_result.head()

,소계,2011년 이전,2012년,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
시군구명,,,,,,,,,,,
동대문구,"2,003",NaN,NaN,380626.5265,352523.2585,23108.2471,4995.0209,180432.2529,26996.0977,74792.0700,78644.0852
서대문구,"2,121",565,233.0,391778.5713,359811.0256,20091.6381,11875.9076,198307.1585,36521.1715,68432.4914,93353.4956
영등포구,"2,495",132,121.0,498306.6042,458884.2265,33710.7774,5711.6003,320088.7444,81636.7105,87418.6940,151033.3399

In [16]:
del data_result['2012년']
del data_result['2011년 이전']

In [17]:
data_result.head()

,소계,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
시군구명,,,,,,,,,
동대문구,"2,003",380626.5265,352523.2585,23108.2471,4995.0209,180432.2529,26996.0977,74792.0700,78644.0852
서대문구,"2,121",391778.5713,359811.0256,20091.6381,11875.9076,198307.1585,36521.1715,68432.4914,93353.4956
영등포구,"2,495",498306.6042,458884.2265,33710.7774,5711.6003,320088.7444,81636.7105,87418.6940,151033.3399

In [18]:
data_result['외국인생활인구수'] = data_result['총생활인구수'] - data_result['내국인생활인구수']

In [19]:
data_result['외국인생활인구수비율'] = data_result['외국인생활인구수'] / data_result['총생활인구수'] * 100
data_result['내국인생활인구수비율'] = data_result['내국인생활인구수'] / data_result['총생활인구수'] * 100

In [20]:
data_result.head()

,소계,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수,외국인생활인구수,외국인생활인구수비율,내국인생활인구수비율
시군구명,,,,,,,,,,,,
동대문구,"2,003",380626.5265,352523.2585,23108.2471,4995.0209,180432.2529,26996.0977,74792.0700,78644.0852,28103.2680,7.383423,92.616577
서대문구,"2,121",391778.5713,359811.0256,20091.6381,11875.9076,198307.1585,36521.1715,68432.4914,93353.4956,31967.5457,8.159595,91.840405
영등포구,"2,495",498306.6042,458884.2265,33710.7774,5711.6003,320088.7444,81636.7105,87418.6940,151033.3399,39422.3777,7.911269,92.088731

In [21]:
data_result[data_result['소계'].isnull()]

Empty DataFrame
Columns: [소계, 총생활인구수, 내국인생활인구수, 장기체류외국인인구수, 단기체류외국인인구수, 일최대이동인구수, 서울외유입인구수, 동일자치구행정동간이동인구수, 자치구간이동인구수, 외국인생활인구수, 외국인생활인구수비율, 내국인생활인구수비율]
Index: []

In [22]:
data_result[data_result['외국인생활인구수비율'].isnull()]

Empty DataFrame
Columns: [소계, 총생활인구수, 내국인생활인구수, 장기체류외국인인구수, 단기체류외국인인구수, 일최대이동인구수, 서울외유입인구수, 동일자치구행정동간이동인구수, 자치구간이동인구수, 외국인생활인구수, 외국인생활인구수비율, 내국인생활인구수비율]
Index: []

In [25]:
import numpy as np

In [26]:
data_result[data_result['내국인생활인구수비율'].isnull()]

Empty DataFrame
Columns: [소계, 총생활인구수, 내국인생활인구수, 장기체류외국인인구수, 단기체류외국인인구수, 일최대이동인구수, 서울외유입인구수, 동일자치구행정동간이동인구수, 자치구간이동인구수, 외국인생활인구수, 외국인생활인구수비율, 내국인생활인구수비율]
Index: []

In [27]:
np.corrcoef(data_result['외국인생활인구수비율'], data_result['소계'])

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [28]:
 np.corrcoef(data_result['내국인생활인구수비율'], data_result['소계'])

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [29]:
np.corrcoef(data_result['외국인생활인구수비율'], data_result['내국인생활인구수비율'])

array([[ 1., -1.],
       [-1.,  1.]])

In [30]:
np.corrcoef(data_result['외국인생활인구수비율'], data_result['내국인생활인구수비율'])

array([[ 1., -1.],
       [-1.,  1.]])

In [32]:
data_result.sort_values(by='소계', ascending=False).head(50)

,소계,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수,외국인생활인구수,외국인생활인구수비율,내국인생활인구수비율
시군구명,,,,,,,,,,,,
영등포구,"2,495",498306.6042,458884.2265,33710.7774,5711.6003,320088.7444,81636.7105,87418.6940,151033.3399,39422.3777,7.911269,92.088731
서대문구,"2,121",391778.5713,359811.0256,20091.6381,11875.9076,198307.1585,36521.1715,68432.4914,93353.4956,31967.5457,8.159595,91.840405
동대문구,"2,003",380626.5265,352523.2585,23108.2471,4995.0209,180432.2529,26996.0977,74792.0700,78644.0852,28103.2680,7.383423,92.616577