In [53]:
import pandas as pd
import numpy as np

In [54]:
pop_seoul=pd.read_excel('C:/Users/woowahan/Documents/data/Python/datamassage/pop_seoul.xlsx', enconding='utf-8' )

In [55]:
pop_seoul.head()

,기준일ID,시군구코드,시군구명,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
0,20201218,11000,서울시,1.090282e+07,1.043842e+07,379579.3655,84819.9178,1.116026e+07,1.063678e+07,1.112032e+07,1.074746e+07,5.574969e+06,1.250712e+06,2.058656e+06,2.265601e+06
1,20201218,11110,종로구,2.851009e+05,2.670721e+05,15486.6770,2542.1083,3.701797e+05,2.206032e+05,3.494647e+05,2.391268e+05,2.337545e+05,5.314368e+04,3.233038e+04,1.482805e+05
2,20201218,11140,중구,2.783933e+05,2.520432e+05,18976.8810,7373.2515,3.961259e+05,1.902078e+05,3.685337e+05,2.140073e+05,2.776604e+05,6.765127e+04,3.103768e+04,1.789715e+05
3,20201218,11170,용산구,3.013044e+05,2.797843e+05,18205.2012,3314.9219,3.232275e+05,2.766007e+05,3.209562e+05,2.872674e+05,1.695602e+05,4.111844e+04,4.683125e+04,8.161048e+04
4,20201218,11200,성동구,3.594109e+05,3.425431e+05,15032.8670,1834.9967,3.756175e+05,3.388085e+05,3.740402e+05,3.489614e+05,1.918945e+05,3.481653e+04,5.858649e+04,9.849144e+04

In [56]:
pop_seoul.drop([0], inplace=True)

In [57]:
pop_seoul.head()

,기준일ID,시군구코드,시군구명,총생활인구수,내국인생활인구수,장기체류외국인인구수,단기체류외국인인구수,일최대인구수,일최소인구수,주간인구수(09~18),야간인구수(19~08),일최대이동인구수,서울외유입인구수,동일자치구행정동간이동인구수,자치구간이동인구수
1,20201218,11110,종로구,285100.9320,267072.1466,15486.6770,2542.1083,370179.7235,220603.1741,349464.6706,239126.8330,233754.5464,53143.6773,32330.3759,148280.4932
2,20201218,11140,중구,278393.2846,252043.1521,18976.8810,7373.2515,396125.9320,190207.8422,368533.6508,214007.3086,277660.4211,67651.2659,31037.6768,178971.4784
3,20201218,11170,용산구,301304.4117,279784.2886,18205.2012,3314.9219,323227.4861,276600.6972,320956.2116,287267.4119,169560.1646,41118.4382,46831.2450,81610.4814
4,20201218,11200,성동구,359410.9331,342543.0694,15032.8670,1834.9967,375617.4780,338808.5386,374040.2438,348961.4254,191894.4580,34816.5301,58586.4911,98491.4368
5,20201218,11215,광진구,380801.7989,359331.6158,19795.5445,1674.6386,396609.8374,356702.2293,363855.8033,392906.0814,161528.0975,28939.9726,73814.0754,58774.0495

In [58]:
pop_seoul['시군구명'].unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구'], dtype=object)

In [59]:
pop_seoul = pop_seoul.loc[:,['시군구명','총생활인구수','내국인생활인구수','자치구간이동인구수']]

In [60]:
pop_seoul

    시군구명       총생활인구수     내국인생활인구수    자치구간이동인구수
1    종로구  285100.9320  267072.1466  148280.4932
2     중구  278393.2846  252043.1521  178971.4784
3    용산구  301304.4117  279784.2886   81610.4814
4    성동구  359410.9331  342543.0694   98491.4368
5    광진구  380801.7989  359331.6158   58774.0495
6   동대문구  380626.5265  352523.2585   78644.0852
7    중랑구  363625.5662  356752.9155   37585.4937
8    성북구  442839.3882  423466.9152   67140.4480
9    강북구  303600.4687  297630.8965   42810.1096
10   도봉구  280932.0730  277410.3784   40171.6670
11   노원구  523749.5455  517147.5301   51151.8217
12   은평구  451182.6804  443588.3717   32814.6184
13  서대문구  391778.5713  359811.0256   93353.4956
14   마포구  465006.1831  440397.4417  118802.5878
15   양천구  396299.2014  389546.8481   57200.6449
16   강서구  552367.0525  538674.1373   61794.5566
17   구로구  421796.4731  389060.1354   64908.6001
18   금천구  243863.6392  225054.6774   52683.7942
19  영등포구  498306.6042  458884.2265  151033.3399
20   동작구  396958.4707  380318.2077   59818.0233
21   관악구  500782.4162  476404.2193   54487.7683
22   서초구  589283.4725  571307.4027  190830.4441
23   강남구  822182.9472  795048.6507  292242.3241
24   송파구  761682.7816  743595.4558  110336.7426
25   강동구  510946.4218  501025.5936   43450.3133

In [61]:
pop_seoul['외국인생활인구수'] = pop_seoul['총생활인구수']-pop_seoul['내국인생활인구수']

In [62]:
pop_seoul

    시군구명       총생활인구수     내국인생활인구수    자치구간이동인구수    외국인생활인구수
1    종로구  285100.9320  267072.1466  148280.4932  18028.7854
2     중구  278393.2846  252043.1521  178971.4784  26350.1325
3    용산구  301304.4117  279784.2886   81610.4814  21520.1231
4    성동구  359410.9331  342543.0694   98491.4368  16867.8637
5    광진구  380801.7989  359331.6158   58774.0495  21470.1831
6   동대문구  380626.5265  352523.2585   78644.0852  28103.2680
7    중랑구  363625.5662  356752.9155   37585.4937   6872.6507
8    성북구  442839.3882  423466.9152   67140.4480  19372.4730
9    강북구  303600.4687  297630.8965   42810.1096   5969.5722
10   도봉구  280932.0730  277410.3784   40171.6670   3521.6946
11   노원구  523749.5455  517147.5301   51151.8217   6602.0154
12   은평구  451182.6804  443588.3717   32814.6184   7594.3087
13  서대문구  391778.5713  359811.0256   93353.4956  31967.5457
14   마포구  465006.1831  440397.4417  118802.5878  24608.7414
15   양천구  396299.2014  389546.8481   57200.6449   6752.3533
16   강서구  552367.0525  538674.1373   61794.5566  13692.9152
17   구로구  421796.4731  389060.1354   64908.6001  32736.3377
18   금천구  243863.6392  225054.6774   52683.7942  18808.9618
19  영등포구  498306.6042  458884.2265  151033.3399  39422.3777
20   동작구  396958.4707  380318.2077   59818.0233  16640.2630
21   관악구  500782.4162  476404.2193   54487.7683  24378.1969
22   서초구  589283.4725  571307.4027  190830.4441  17976.0698
23   강남구  822182.9472  795048.6507  292242.3241  27134.2965
24   송파구  761682.7816  743595.4558  110336.7426  18087.3258
25   강동구  510946.4218  501025.5936   43450.3133   9920.8282

In [63]:
pop_seoul[pop_seoul['시군구명'].isnull()]

Empty DataFrame
Columns: [시군구명, 총생활인구수, 내국인생활인구수, 자치구간이동인구수, 외국인생활인구수]
Index: []

In [64]:
pop_seoul['외국인생활인구수비율'] = pop_seoul['외국인생활인구수']/pop_seoul['총생활인구수']*100
pop_seoul['내국인생활인구수비율'] = pop_seoul['내국인생활인구수']/pop_seoul['총생활인구수']*100
pop_seoul['자치구간이동인구수비율'] = pop_seoul['자치구간이동인구수']/pop_seoul['총생활인구수']*100

In [65]:
pop_seoul

,시군구명,총생활인구수,내국인생활인구수,자치구간이동인구수,외국인생활인구수,외국인생활인구수비율,내국인생활인구수비율,자치구간이동인구수비율
1,종로구,285100.9320,267072.1466,148280.4932,18028.7854,6.323650,93.676350,52.009824
2,중구,278393.2846,252043.1521,178971.4784,26350.1325,9.465075,90.534925,64.287283
3,용산구,301304.4117,279784.2886,81610.4814,21520.1231,7.142319,92.857681,27.085724
4,성동구,359410.9331,342543.0694,98491.4368,16867.8637,4.693197,95.306803,27.403573
5,광진구,380801.7989,359331.6158,58774.0495,21470.1831,5.638152,94.361848,15.434289
6,동대문구,380626.5265,352523.2585,78644.0852,28103.2680,7.383423,92.616577,20.661746
7,중랑구,363625.5662,356752.9155,37585.4937,6872.6507,1.890035,98.109965,10.336318
8,성북구,442839.3882,423466.9152,67140.4480,19372.4730,4.374605,95.625395,15.161354
9,강북구,303600.4687,297630.8965,42810.1096,5969.5722,1.966259,98.033741,14.100805
10,도봉구,280932.0730,277410.3784,40171.6670,3521.6946,1.253575,98.746425,14.299424
11,노원구,523749.5455,517147.5301,51151.8217,6602.0154,1.260529,98.739471,9.766466
12,은평구,451182.6804,443588.3717,32814.6184,7594.3087,1.683200,98.316800,7.273023
13,서대문구,391778.5713,359811.0256,93353.4956,31967.5457,8.159595,91.840405,23.828127
14,마포구,465006.1831,440397.4417,118802.5878,24608.7414,5.292132,94.707868,25.548604
15,양천구,396299.2014,389546.8481,57200.6449,6752.3533,1.703852,98.296148,14.433702
16,강서구,552367.0525,538674.1373,61794.5566,13692.9152,2.478952,97.521048,11.187227
17,구로구,421796.4731,389060.1354,64908.6001,32736.3377,7.761169,92.238831,15.388607
18,금천구,243863.6392,225054.6774,52683.7942,18808.9618,7.712901,92.287099,21.603792
19,영등포구,498306.6042,458884.2265,151033.3399,39422.3777,7.911269,92.088731,30.309319
20,동작구,396958.4707,380318.2077,59818.0233,16640.2630,4.191941,95.808059,15.069089
21,관악구,500782.4162,476404.2193,54487.7683,24378.1969,4.868022,95.131978,10.880527
22,서초구,589283.4725,571307.4027,190830.4441,17976.0698,3.050496,96.949504,32.383471
23,강남구,822182.9472,795048.6507,292242.3241,27134.2965,3.300275,96.699725,35.544683
24,송파구,761682.7816,743595.4558,110336.7426,18087.3258,2.374653,97.625347,14.485918
25,강동구,510946.4218,501025.5936,43450.3133,9920.8282,1.941657,98.058343,8.503888

In [69]:
pop_seoul.sort_values(by='총생활인구수', ascending=False).head(5)

,시군구명,총생활인구수,내국인생활인구수,자치구간이동인구수,외국인생활인구수,외국인생활인구수비율,내국인생활인구수비율,자치구간이동인구수비율
23,강남구,822182.9472,795048.6507,292242.3241,27134.2965,3.300275,96.699725,35.544683
24,송파구,761682.7816,743595.4558,110336.7426,18087.3258,2.374653,97.625347,14.485918
22,서초구,589283.4725,571307.4027,190830.4441,17976.0698,3.050496,96.949504,32.383471
16,강서구,552367.0525,538674.1373,61794.5566,13692.9152,2.478952,97.521048,11.187227
11,노원구,523749.5455,517147.5301,51151.8217,6602.0154,1.260529,98.739471,9.766466

In [72]:
pop_seoul.sort_values(by='외국인생활인구수', ascending=False).head(5)

,시군구명,총생활인구수,내국인생활인구수,자치구간이동인구수,외국인생활인구수,외국인생활인구수비율,내국인생활인구수비율,자치구간이동인구수비율
19,영등포구,498306.6042,458884.2265,151033.3399,39422.3777,7.911269,92.088731,30.309319
17,구로구,421796.4731,389060.1354,64908.6001,32736.3377,7.761169,92.238831,15.388607
13,서대문구,391778.5713,359811.0256,93353.4956,31967.5457,8.159595,91.840405,23.828127
6,동대문구,380626.5265,352523.2585,78644.0852,28103.2680,7.383423,92.616577,20.661746
23,강남구,822182.9472,795048.6507,292242.3241,27134.2965,3.300275,96.699725,35.544683

In [73]:
pop_seoul.sort_values(by='외국인생활인구수비율', ascending=False).head(5)

,시군구명,총생활인구수,내국인생활인구수,자치구간이동인구수,외국인생활인구수,외국인생활인구수비율,내국인생활인구수비율,자치구간이동인구수비율
2,중구,278393.2846,252043.1521,178971.4784,26350.1325,9.465075,90.534925,64.287283
13,서대문구,391778.5713,359811.0256,93353.4956,31967.5457,8.159595,91.840405,23.828127
19,영등포구,498306.6042,458884.2265,151033.3399,39422.3777,7.911269,92.088731,30.309319
17,구로구,421796.4731,389060.1354,64908.6001,32736.3377,7.761169,92.238831,15.388607
18,금천구,243863.6392,225054.6774,52683.7942,18808.9618,7.712901,92.287099,21.603792

In [74]:
pop_seoul.sort_values(by='내국인생활인구수비율', ascending=False).head(5)

,시군구명,총생활인구수,내국인생활인구수,자치구간이동인구수,외국인생활인구수,외국인생활인구수비율,내국인생활인구수비율,자치구간이동인구수비율
10,도봉구,280932.0730,277410.3784,40171.6670,3521.6946,1.253575,98.746425,14.299424
11,노원구,523749.5455,517147.5301,51151.8217,6602.0154,1.260529,98.739471,9.766466
12,은평구,451182.6804,443588.3717,32814.6184,7594.3087,1.683200,98.316800,7.273023
15,양천구,396299.2014,389546.8481,57200.6449,6752.3533,1.703852,98.296148,14.433702
7,중랑구,363625.5662,356752.9155,37585.4937,6872.6507,1.890035,98.109965,10.336318